// 都道府県データ（code は SVG 側の data-code と一致させる）
// hint: その県を象徴する、最も分かりやすいものをひとつだけ
// famousPerson: その県ゆかりの、歴史的に最も有名な人物をひとつだけ
const PREFECTURES = [
  { code: "1", name: "北海道", kana: "ほっかいどう", capital: "札幌市", capitalKana: "さっぽろし", hint: "じゃがいも", famousPerson: "松浦武四郎", pin: { x: 663.4, y: 210 }, labelPos: { x: 722.2, y: 163.7 } },
  { code: "2", name: "青森県", kana: "あおもりけん", capital: "青森市", capitalKana: "あおもりし", hint: "りんご", famousPerson: "棟方志功", pin: { x: 646.2, y: 329.2 }, labelPos: { x: 647.2, y: 333.2 } },
  { code: "3", name: "岩手県", kana: "いわてけん", capital: "盛岡市", capitalKana: "もりおかし", hint: "わんこそば", famousPerson: "宮沢賢治", pin: { x: 673.2, y: 381.4 }, labelPos: { x: 676.1, y: 409.5 } },
  { code: "4", name: "宮城県", kana: "みやぎけん", capital: "仙台市", capitalKana: "せんだいし", hint: "牛タン", famousPerson: "伊達政宗", pin: { x: 662.4, y: 490.5 }, labelPos: { x: 657.5, y: 484.4 } },
  { code: "5", name: "秋田県", kana: "あきたけん", capital: "秋田市", capitalKana: "あきたし", hint: "きりたんぽ", famousPerson: "小野小町", pin: { x: 612, y: 393.9 }, labelPos: { x: 628.5, y: 401.5 } },
  { code: "6", name: "山形県", kana: "やまがたけん", capital: "山形市", capitalKana: "やまがたし", hint: "さくらんぼ", famousPerson: "上杉鷹山", pin: { x: 618.3, y: 512.8 }, labelPos: { x: 616, y: 485.1 } },
  { code: "7", name: "福島県", kana: "ふくしまけん", capital: "福島市", capitalKana: "ふくしまし", hint: "桃", famousPerson: "野口英世", pin: { x: 627.5, y: 530 }, labelPos: { x: 624.3, y: 553.9 } },
  { code: "8", name: "茨城県", kana: "いばらきけん", capital: "水戸市", capitalKana: "みとし", hint: "納豆", famousPerson: "徳川光圀", pin: { x: 635.6, y: 607.9 }, labelPos: { x: 631, y: 622.8 } },
  { code: "9", name: "栃木県", kana: "とちぎけん", capital: "宇都宮市", capitalKana: "うつのみやし", hint: "いちご", famousPerson: "田中正造", pin: { x: 603.5, y: 602.7 }, labelPos: { x: 604.3, y: 598.6 } },
  { code: "10", name: "群馬県", kana: "ぐんまけん", capital: "前橋市", capitalKana: "まえばしし", hint: "こんにゃく", famousPerson: "内村鑑三", pin: { x: 561.5, y: 624.6 }, labelPos: { x: 561.2, y: 611.8 } },
  { code: "11", name: "埼玉県", kana: "さいたまけん", capital: "さいたま市", capitalKana: "さいたまし", hint: "ねぎ", famousPerson: "渋沢栄一", pin: { x: 581.9, y: 650.9 }, labelPos: { x: 581.7, y: 643.5 } },
  { code: "12", name: "千葉県", kana: "ちばけん", capital: "千葉市", capitalKana: "ちばし", hint: "落花生", famousPerson: "伊能忠敬", pin: { x: 624.1, y: 663.8 }, labelPos: { x: 626.8, y: 674.5 } },
  { code: "13", name: "東京都", kana: "とうきょうと", capital: "新宿区", capitalKana: "しんじゅくく", hint: "東京タワー", famousPerson: "勝海舟", pin: { x: 588.2, y: 663.1 }, labelPos: { x: 586, y: 661.6 } },
  { code: "14", name: "神奈川県", kana: "かながわけん", capital: "横浜市", capitalKana: "よこはまし", hint: "しゅうまい", famousPerson: "源頼朝", pin: { x: 588.9, y: 675.3 }, labelPos: { x: 581.2, y: 680.7 } },
  { code: "15", name: "新潟県", kana: "にいがたけん", capital: "新潟市", capitalKana: "にいがたし", hint: "コシヒカリ", famousPerson: "上杉謙信", pin: { x: 552.3, y: 533.7 }, labelPos: { x: 559.1, y: 548.4 } },
  { code: "16", name: "富山県", kana: "とやまけん", capital: "富山市", capitalKana: "とやまし", hint: "ますずし", famousPerson: "藤子・F・不二雄", pin: { x: 474.8, y: 596.3 }, labelPos: { x: 473.3, y: 603.3 } },
  { code: "17", name: "石川県", kana: "いしかわけん", capital: "金沢市", capitalKana: "かなざわし", hint: "金箔", famousPerson: "前田利家", pin: { x: 449, y: 626.2 }, labelPos: { x: 446.8, y: 595.4 } },
  { code: "18", name: "福井県", kana: "ふくいけん", capital: "福井市", capitalKana: "ふくいし", hint: "恐竜", famousPerson: "松平春嶽", pin: { x: 414.4, y: 643.3 }, labelPos: { x: 418.1, y: 654 } },
  { code: "19", name: "山梨県", kana: "やまなしけん", capital: "甲府市", capitalKana: "こうふし", hint: "ぶどう", famousPerson: "武田信玄", pin: { x: 545.3, y: 664.2 }, labelPos: { x: 543.2, y: 668.6 } },
  { code: "20", name: "長野県", kana: "ながのけん", capital: "長野市", capitalKana: "ながのし", hint: "そば", famousPerson: "真田幸村", pin: { x: 512.7, y: 595.9 }, labelPos: { x: 513.1, y: 635.9 } },
  { code: "21", name: "岐阜県", kana: "ぎふけん", capital: "岐阜市", capitalKana: "ぎふし", hint: "飛騨牛", famousPerson: "織田信長", pin: { x: 460.5, y: 686.9 }, labelPos: { x: 461.9, y: 658.3 } },
  { code: "22", name: "静岡県", kana: "しずおかけん", capital: "静岡市", capitalKana: "しずおかし", hint: "お茶", famousPerson: "徳川家康", pin: { x: 531.8, y: 704.5 }, labelPos: { x: 529.1, y: 707.4 } },
  { code: "23", name: "愛知県", kana: "あいちけん", capital: "名古屋市", capitalKana: "なごやし", hint: "味噌カツ", famousPerson: "豊田佐吉", pin: { x: 462.6, y: 706.2 }, labelPos: { x: 469.8, y: 706.5 } },
  { code: "24", name: "三重県", kana: "みえけん", capital: "津市", capitalKana: "つし", hint: "松阪牛", famousPerson: "松尾芭蕉", pin: { x: 431.5, y: 716.6 }, labelPos: { x: 425.5, y: 738.8 } },
  { code: "25", name: "滋賀県", kana: "しがけん", capital: "大津市", capitalKana: "おおつし", hint: "琵琶湖", famousPerson: "石田三成", pin: { x: 406.5, y: 712.8 }, labelPos: { x: 413.1, y: 694.5 } },
  { code: "26", name: "京都府", kana: "きょうとふ", capital: "京都市", capitalKana: "きょうとし", hint: "抹茶", famousPerson: "紫式部", pin: { x: 383.5, y: 702.9 }, labelPos: { x: 376.6, y: 691 } },
  { code: "27", name: "大阪府", kana: "おおさかふ", capital: "大阪市", capitalKana: "おおさかし", hint: "たこ焼き", famousPerson: "豊臣秀吉", pin: { x: 376.9, y: 726.4 }, labelPos: { x: 379.2, y: 732.3 } },
  { code: "28", name: "兵庫県", kana: "ひょうごけん", capital: "神戸市", capitalKana: "こうべし", hint: "神戸牛", famousPerson: "平清盛", pin: { x: 364.6, y: 707.7 }, labelPos: { x: 343.9, y: 700.4 } },
  { code: "29", name: "奈良県", kana: "ならけん", capital: "奈良市", capitalKana: "ならし", hint: "鹿", famousPerson: "聖徳太子", pin: { x: 399, y: 731.1 }, labelPos: { x: 398, y: 752.2 } },
  { code: "30", name: "和歌山県", kana: "わかやまけん", capital: "和歌山市", capitalKana: "わかやまし", hint: "みかん", famousPerson: "松下幸之助", pin: { x: 377.3, y: 757.1 }, labelPos: { x: 378.3, y: 777.5 } },
  { code: "31", name: "鳥取県", kana: "とっとりけん", capital: "鳥取市", capitalKana: "とっとりし", hint: "砂丘", famousPerson: "水木しげる", pin: { x: 317.7, y: 680.3 }, labelPos: { x: 294.3, y: 681.9 } },
  { code: "32", name: "島根県", kana: "しまねけん", capital: "松江市", capitalKana: "まつえし", hint: "出雲大社", famousPerson: "小泉八雲", pin: { x: 248.5, y: 696.7 }, labelPos: { x: 223.2, y: 701 } },
  { code: "33", name: "岡山県", kana: "おかやまけん", capital: "岡山市", capitalKana: "おかやまし", hint: "マスカット", famousPerson: "宇喜多秀家", pin: { x: 298.9, y: 726.8 }, labelPos: { x: 290.7, y: 711.2 } },
  { code: "34", name: "広島県", kana: "ひろしまけん", capital: "広島市", capitalKana: "ひろしまし", hint: "お好み焼き", famousPerson: "毛利元就", pin: { x: 225.3, y: 742.6 }, labelPos: { x: 235.6, y: 726.2 } },
  { code: "35", name: "山口県", kana: "やまぐちけん", capital: "山口市", capitalKana: "やまぐちし", hint: "ふぐ", famousPerson: "吉田松陰", pin: { x: 172.3, y: 761.2 }, labelPos: { x: 168.5, y: 748.9 } },
  { code: "36", name: "徳島県", kana: "とくしまけん", capital: "徳島市", capitalKana: "とくしまし", hint: "すだち", famousPerson: "賀川豊彦", pin: { x: 323.4, y: 766.3 }, labelPos: { x: 310.4, y: 775.3 } },
  { code: "37", name: "香川県", kana: "かがわけん", capital: "高松市", capitalKana: "たかまつし", hint: "うどん", famousPerson: "平賀源内", pin: { x: 299.1, y: 748.8 }, labelPos: { x: 297, y: 756.1 } },
  { code: "38", name: "愛媛県", kana: "えひめけん", capital: "松山市", capitalKana: "まつやまし", hint: "タオル", famousPerson: "正岡子規", pin: { x: 228.3, y: 784 }, labelPos: { x: 235.9, y: 792.2 } },
  { code: "39", name: "高知県", kana: "こうちけん", capital: "高知市", capitalKana: "こうちし", hint: "かつお", famousPerson: "坂本龍馬", pin: { x: 272.3, y: 798.4 }, labelPos: { x: 263.3, y: 805.1 } },
  { code: "40", name: "福岡県", kana: "ふくおかけん", capital: "福岡市", capitalKana: "ふくおかし", hint: "明太子", famousPerson: "黒田官兵衛", pin: { x: 105.2, y: 779.2 }, labelPos: { x: 118.6, y: 790.5 } },
  { code: "41", name: "佐賀県", kana: "さがけん", capital: "佐賀市", capitalKana: "さがし", hint: "有田焼", famousPerson: "大隈重信", pin: { x: 91.1, y: 811.1 }, labelPos: { x: 88.4, y: 803.2 } },
  { code: "42", name: "長崎県", kana: "ながさきけん", capital: "長崎市", capitalKana: "ながさきし", hint: "カステラ", famousPerson: "シーボルト", pin: { x: 75.3, y: 831.7 }, labelPos: { x: 77.3, y: 824.6 } },
  { code: "43", name: "熊本県", kana: "くまもとけん", capital: "熊本市", capitalKana: "くまもとし", hint: "くまモン", famousPerson: "加藤清正", pin: { x: 115.9, y: 836.8 }, labelPos: { x: 124.4, y: 847.1 } },
  { code: "44", name: "大分県", kana: "おおいたけん", capital: "大分市", capitalKana: "おおいたし", hint: "温泉", famousPerson: "大友宗麟", pin: { x: 162.9, y: 810.6 }, labelPos: { x: 158.6, y: 813.6 } },
  { code: "45", name: "宮崎県", kana: "みやざきけん", capital: "宮崎市", capitalKana: "みやざきし", hint: "マンゴー", famousPerson: "神武天皇", pin: { x: 154.8, y: 884 }, labelPos: { x: 147.7, y: 878 } },
  { code: "46", name: "鹿児島県", kana: "かごしまけん", capital: "鹿児島市", capitalKana: "かごしまし", hint: "さつまいも", famousPerson: "西郷隆盛", pin: { x: 101.1, y: 917.4 }, labelPos: { x: 110.2, y: 913.6 } },
  { code: "47", name: "沖縄県", kana: "おきなわけん", capital: "那覇市", capitalKana: "なはし", hint: "シーサー", famousPerson: "尚巴志王", pin: { x: 304.4, y: 221.7 }, labelPos: { x: 309.8, y: 209.9 } },
];

// 地方の区分（北海道・沖縄は単独で覚えやすいため地方編には含めない）
const REGIONS = [
  { id: "tohoku", label: "東北編", codes: ["2", "3", "4", "5", "6", "7"] },
  {
    id: "kanto-koshinetsu",
    label: "関東甲信越編",
    codes: ["8", "9", "10", "11", "12", "13", "14", "15", "19", "20"],
  },
  { id: "chubu", label: "中部編", codes: ["16", "17", "18", "21", "22", "23"] },
  { id: "kinki", label: "近畿編", codes: ["24", "25", "26", "27", "28", "29", "30"] },
  { id: "chugoku", label: "中国編", codes: ["31", "32", "33", "34", "35"] },
  { id: "shikoku", label: "四国編", codes: ["36", "37", "38", "39"] },
  { id: "kyushu", label: "九州編", codes: ["40", "41", "42", "43", "44", "45", "46"] },
];
