// 都道府県データ（code は SVG 側の data-code と一致させる）
// hint: その県を象徴する、最も分かりやすいものをひとつだけ
const PREFECTURES = [
  { code: "1", name: "北海道", kana: "ほっかいどう", capital: "札幌市", capitalKana: "さっぽろし", hint: "じゃがいも" },
  { code: "2", name: "青森県", kana: "あおもりけん", capital: "青森市", capitalKana: "あおもりし", hint: "りんご" },
  { code: "3", name: "岩手県", kana: "いわてけん", capital: "盛岡市", capitalKana: "もりおかし", hint: "わんこそば" },
  { code: "4", name: "宮城県", kana: "みやぎけん", capital: "仙台市", capitalKana: "せんだいし", hint: "牛タン" },
  { code: "5", name: "秋田県", kana: "あきたけん", capital: "秋田市", capitalKana: "あきたし", hint: "きりたんぽ" },
  { code: "6", name: "山形県", kana: "やまがたけん", capital: "山形市", capitalKana: "やまがたし", hint: "さくらんぼ" },
  { code: "7", name: "福島県", kana: "ふくしまけん", capital: "福島市", capitalKana: "ふくしまし", hint: "桃" },
  { code: "8", name: "茨城県", kana: "いばらきけん", capital: "水戸市", capitalKana: "みとし", hint: "納豆" },
  { code: "9", name: "栃木県", kana: "とちぎけん", capital: "宇都宮市", capitalKana: "うつのみやし", hint: "いちご" },
  { code: "10", name: "群馬県", kana: "ぐんまけん", capital: "前橋市", capitalKana: "まえばしし", hint: "こんにゃく" },
  { code: "11", name: "埼玉県", kana: "さいたまけん", capital: "さいたま市", capitalKana: "さいたまし", hint: "ねぎ" },
  { code: "12", name: "千葉県", kana: "ちばけん", capital: "千葉市", capitalKana: "ちばし", hint: "落花生" },
  { code: "13", name: "東京都", kana: "とうきょうと", capital: "新宿区", capitalKana: "しんじゅくく", hint: "東京タワー" },
  { code: "14", name: "神奈川県", kana: "かながわけん", capital: "横浜市", capitalKana: "よこはまし", hint: "しゅうまい" },
  { code: "15", name: "新潟県", kana: "にいがたけん", capital: "新潟市", capitalKana: "にいがたし", hint: "コシヒカリ" },
  { code: "16", name: "富山県", kana: "とやまけん", capital: "富山市", capitalKana: "とやまし", hint: "ますずし" },
  { code: "17", name: "石川県", kana: "いしかわけん", capital: "金沢市", capitalKana: "かなざわし", hint: "金箔" },
  { code: "18", name: "福井県", kana: "ふくいけん", capital: "福井市", capitalKana: "ふくいし", hint: "恐竜" },
  { code: "19", name: "山梨県", kana: "やまなしけん", capital: "甲府市", capitalKana: "こうふし", hint: "ぶどう" },
  { code: "20", name: "長野県", kana: "ながのけん", capital: "長野市", capitalKana: "ながのし", hint: "そば" },
  { code: "21", name: "岐阜県", kana: "ぎふけん", capital: "岐阜市", capitalKana: "ぎふし", hint: "飛騨牛" },
  { code: "22", name: "静岡県", kana: "しずおかけん", capital: "静岡市", capitalKana: "しずおかし", hint: "お茶" },
  { code: "23", name: "愛知県", kana: "あいちけん", capital: "名古屋市", capitalKana: "なごやし", hint: "味噌カツ" },
  { code: "24", name: "三重県", kana: "みえけん", capital: "津市", capitalKana: "つし", hint: "松阪牛" },
  { code: "25", name: "滋賀県", kana: "しがけん", capital: "大津市", capitalKana: "おおつし", hint: "琵琶湖" },
  { code: "26", name: "京都府", kana: "きょうとふ", capital: "京都市", capitalKana: "きょうとし", hint: "抹茶" },
  { code: "27", name: "大阪府", kana: "おおさかふ", capital: "大阪市", capitalKana: "おおさかし", hint: "たこ焼き" },
  { code: "28", name: "兵庫県", kana: "ひょうごけん", capital: "神戸市", capitalKana: "こうべし", hint: "神戸牛" },
  { code: "29", name: "奈良県", kana: "ならけん", capital: "奈良市", capitalKana: "ならし", hint: "鹿" },
  { code: "30", name: "和歌山県", kana: "わかやまけん", capital: "和歌山市", capitalKana: "わかやまし", hint: "みかん" },
  { code: "31", name: "鳥取県", kana: "とっとりけん", capital: "鳥取市", capitalKana: "とっとりし", hint: "砂丘" },
  { code: "32", name: "島根県", kana: "しまねけん", capital: "松江市", capitalKana: "まつえし", hint: "出雲大社" },
  { code: "33", name: "岡山県", kana: "おかやまけん", capital: "岡山市", capitalKana: "おかやまし", hint: "マスカット" },
  { code: "34", name: "広島県", kana: "ひろしまけん", capital: "広島市", capitalKana: "ひろしまし", hint: "お好み焼き" },
  { code: "35", name: "山口県", kana: "やまぐちけん", capital: "山口市", capitalKana: "やまぐちし", hint: "ふぐ" },
  { code: "36", name: "徳島県", kana: "とくしまけん", capital: "徳島市", capitalKana: "とくしまし", hint: "すだち" },
  { code: "37", name: "香川県", kana: "かがわけん", capital: "高松市", capitalKana: "たかまつし", hint: "うどん" },
  { code: "38", name: "愛媛県", kana: "えひめけん", capital: "松山市", capitalKana: "まつやまし", hint: "タオル" },
  { code: "39", name: "高知県", kana: "こうちけん", capital: "高知市", capitalKana: "こうちし", hint: "かつお" },
  { code: "40", name: "福岡県", kana: "ふくおかけん", capital: "福岡市", capitalKana: "ふくおかし", hint: "明太子" },
  { code: "41", name: "佐賀県", kana: "さがけん", capital: "佐賀市", capitalKana: "さがし", hint: "有田焼" },
  { code: "42", name: "長崎県", kana: "ながさきけん", capital: "長崎市", capitalKana: "ながさきし", hint: "カステラ" },
  { code: "43", name: "熊本県", kana: "くまもとけん", capital: "熊本市", capitalKana: "くまもとし", hint: "くまモン" },
  { code: "44", name: "大分県", kana: "おおいたけん", capital: "大分市", capitalKana: "おおいたし", hint: "温泉" },
  { code: "45", name: "宮崎県", kana: "みやざきけん", capital: "宮崎市", capitalKana: "みやざきし", hint: "マンゴー" },
  { code: "46", name: "鹿児島県", kana: "かごしまけん", capital: "鹿児島市", capitalKana: "かごしまし", hint: "さつまいも" },
  { code: "47", name: "沖縄県", kana: "おきなわけん", capital: "那覇市", capitalKana: "なはし", hint: "シーサー" },
];

// 地方の区分（北海道・沖縄は単独で覚えやすいため地方編には含めない）
const REGIONS = [
  { id: "tohoku", label: "東北編", codes: ["2", "3", "4", "5", "6", "7"] },
  {
    id: "kanto-koshinetsu",
    label: "関東甲信越編",
    codes: ["8", "9", "10", "11", "12", "13", "14", "15", "19", "20"],
  },
  { id: "chubu", label: "中部編", codes: ["16", "17", "18", "21", "22", "23"] },
  { id: "kinki", label: "近畿編", codes: ["24", "25", "26", "27", "28", "29", "30"] },
  { id: "chugoku", label: "中国編", codes: ["31", "32", "33", "34", "35"] },
  { id: "shikoku", label: "四国編", codes: ["36", "37", "38", "39"] },
  { id: "kyushu", label: "九州編", codes: ["40", "41", "42", "43", "44", "45", "46"] },
];
